name: LiCo build

on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build and pack
      run: dotnet pack --configuration Release -o ./output/
    - name: Run tests
      run: echo "No tests yet!"
    - name: Deploy Nuget Package
      run: dotnet nuget push './output/*.nupkg' -k $NUGET_API_KEY -s "https://api.nuget.org/v3/index.json"
      if: matrix.os == 'windows-latest' && github.event_name != 'pull_request'