name: LiCo build

on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build and pack
      run: dotnet pack --configuration Release -o ./output/
    - name: Run tests
      run: echo "No tests yet!"
    - name: Setup NuGet.exe
      if: github.event_name == 'push' && matrix.os == 'windows-latest'
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    - name: Publish packages
      if: github.event_name == 'push' && matrix.os == 'windows-latest'
      run: nuget push ./output/*.nupkg -src https://api.nuget.org/v3/index.json -SkipDuplicate
      shell: bash